[imaging_specs]
local_storage_directory = "C:\\584_d15_round2"
subject_id = "test"
tile_prefix = "584_d15_round2"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 15
z_step_size_um = 0.209
volume_x_um = 11000.0
volume_y_um = 200.0
volume_z_um = 8000
laser_wavelengths = [ 488, 561, 638,]
camera_streams = [ 0,]
external_storage_directory = "Y:\\584_d15_round2"
filetype = "Tiff"

[experiment_specs]
experimenters_name = "Kevin Cao"
immersion_medium = "PBS"
immersion_medium_refractive_index = 1.33

[tile_specs]
x_field_of_view_um = 686.592
y_field_of_view_um = 686.592
row_count_pixels = 2304
column_count_pixels = 2304
data_type = "uint16"

[design_specs]
slit_width_pixels = 150

[stage_specs]
backlash_reset_distance_um = 4

[waveform_specs]
delay_time = 0
rest_time = 0.004
exposure_time = 0.025
line_time_us = 10.850694444444445
pre_buffer_time_s = 0.001
post_buffer_time_s = 0.001
laser_pre_buffer_time_s = 0.001
laser_post_buffer_time_s = 0.001

[daq_ao_names_to_channels]
galvo_y = 0
galvo_x = 2
etl = 4
camera = 6

[daq_driver_kwds]
dev_name = "Dev2"
input_trigger_name = "PFI0"
count_trigger_name = "PFI3"
ao_counter_trigger_name = "PFI2"
update_frequency_hz = 400000.0
livestream_frequency_hz = 30

[tiger_controller_driver_kwds]
com_port = "COM3"

[filter_wheel_kwds]
tiger_axis = 1

[estimates]
tiles_per_second = 15

[camera_specs]
scan_direction = "BACKWARD"
shutter_mode = "LIGHTSHEET"

[tiger_specs.axes]
etl_left_axis = "V"
etl_right_axis = "W"
galvo_left_x_axis = "A"
galvo_left_y_axis = "B"
galvo_right_x_axis = "C"
galvo_right_y_axis = "D"


[channel_specs.main]
driver = "oxxius_laser"
laser = "Splitter"
intensity_mode = 'current'
modulation_mode = 'digital'


[channel_specs.405]
driver = "oxxius_laser"
laser = "OxxiusLaser"
intensity_mode = 'current'
modulation_mode = 'digital'
color = "purple"
filter_index = 1
ao_channel = 12
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.488]
driver = "oxxius_laser"
laser = "OxxiusLaser"
intensity_mode = 'current'
modulation_mode = 'digital'
color = "blue"
filter_index = 2
ao_channel = 11
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.561]
driver = "oxxius_laser"
laser = "OxxiusLaser"
intensity_mode = 'power'
modulation_mode = 'digital'
color = "green"
filter_index = 3
ao_channel = 9
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.638]
driver = "oxxius_laser"
laser = "OxxiusLaser"
intensity_mode = 'current'
modulation_mode = 'digital'
color = "red"
filter_index = 4
ao_channel = 8
disable_voltage = 0.0
enable_voltage = 5.0

[sample_pose_kwds.axis_map]
x = "y"
y = "z"
z = "x"

[channel_specs.405.coeffecients]
1 = 3.218
0 = -57.515

[channel_specs.405.etl]
offset = 1.687
amplitude = 0

[channel_specs.405.galvo]
x_offset = 2.34
x_amplitude = -0.01
y_offset = 2.42
y_amplitude = 1.238

[channel_specs.main.kwds]
port = 'COM7'

[channel_specs.405.kwds]
prefix = "L6"

[channel_specs.488.coeffecients]
1 = 2.3125
0 = -35.09

[channel_specs.488.etl]
offset = 0.799
amplitude = 2.373

[channel_specs.488.galvo]
x_offset = 2.317
x_amplitude = -0.01
y_offset = 2.409
y_amplitude = 1.244

[channel_specs.488.kwds]
prefix = "L5"

[channel_specs.561.etl]
offset = 3.012
amplitude = 0

[channel_specs.561.galvo]
x_offset = 2.315
x_amplitude = -0.02
y_offset = 2.414
y_amplitude = 1.212

[channel_specs.561.kwds]
prefix = "L3"

[channel_specs.638.coeffecients]
1 = 2.237
0 = -29.349

[channel_specs.638.etl]
offset = 3.78
amplitude = 0

[channel_specs.638.galvo]
x_offset = 2.31
x_amplitude = -0.01
y_offset = 2.442
y_amplitude = 1.149

[channel_specs.638.kwds]
prefix = "L1"
