# No repeat values in here!
[imaging_params]
local_storage_directory = 'C:\\test' # Storing on C (ssd) will yield faster file transfers.
external_storage_directory = 'Z:\mesoSPIM'
subject_id = "brain_488" # Specimin name.
tile_prefix = 'tile'  # Zstacks will be named: <tile_prefix>_<x>_<y>_<wavelength>.tiff.
tile_overlap_y_percent = 15
tile_overlap_z_percent = 15
x_step_size_um = 0.25 # x spacing between images. Defaults to same as y,z spacing if not listed.
volume_x_um = 1000 # Sample volume x dimension that we want to stage scan.
volume_y_um = 1000 # Sample volume y dimension that we want to tile.
volume_z_um = 1000 # Sample volume z dimension that we want to tile.
laser_wavelengths = [488]

[design_specs]
slit_width = 120 # pixels
tile_size_um = 2048 # XY image field of view in [um]. This should not change.
sensor_row_count = 2048

# Stage
[sample_stage_specs]
move_time_um = 0.025 # time it takes the stage to move 1[um] and settle.
backlash_reset_distance_um = 4 # [um]

# Signals
[waveform_specs]
start_of_frame_delay = 950e-6 # seconds. Time between external trigger and first hsync.
[waveform_specs.adjustment_galvo]
voltage_setpoint = -0.06

# Laser Channels
[channel_specs.405]
driver = "Vortran"
color = "purple"
filter_index = 1
ao_channel = 0
disable_voltage = 0.0
enable_voltage =  5.0
camera_axis_position = 600 # absolute value in steps.
[channel_specs.405.etl]
delay = 0.0 # seconds. time to advance the etl waveform such that the actual signal arrives on time.
settling_time = 0.025 # seconds. min time for the etl to recover to its start position.
min_voltage = 2.49
max_voltage = 2.85
[channel_specs.405.kwds]
port='COMxx'

[channel_specs.488]
driver = "Vortran"
color = "blue"
filter_index = 2
ao_channel = 2
disable_voltage = 0.0
enable_voltage =  5.0
camera_axis_position = 1300 # absolute value in steps. (sending: M N=0)
[channel_specs.488.etl]
delay = 0.0 # seconds.
settling_time = 0.025 # seconds.
min_voltage = 2.37
max_voltage = 2.96
[channel_specs.488.kwds]
port='COMxx'

[channel_specs.552]
driver = "ObisLS"
color = "green"
filter_index = 3
ao_channel = 3
disable_voltage = 0.0
enable_voltage =  5.0
camera_axis_position = 0 # absolute value in steps.
[channel_specs.552.etl]
delay = 0.0 # seconds.
settling_time = 0.025 # seconds.
min_voltage = 2.43
max_voltage = 2.96
[channel_specs.552.kwds]
port='COM15'

[channel_specs.639]
driver = "Vortran"
color = "red"
filter_index = 4
ao_channel = 4
disable_voltage = 0.0
enable_voltage =  5.0
camera_axis_position = 1800 # absolute value in steps.
[channel_specs.639.etl]
delay = 0.0 # seconds. time to advance the etl waveform such that the actual signal arrives on time.
settling_time = 0.025 # seconds. min time for the etl to recover to its start position.
min_voltage = 2.36 #2.43 #2.33 for fluorescein water#2.29 #2.287 good for ch1 no sample # 2.275 #2.58 for ch2 #2.545
max_voltage = 2.98 #2.60 for center, glass chamber #2.92 for fluorescein water# 2.96 good for ch1 no sample # 2.9 #2.95 for ch1 #2.95#2.845 # 2.845#2.825
[channel_specs.639.kwds]
port='COMxx'

[daq_ao_names_to_channels] # lookup table for named hardware to AO channels
etl = 1
galvo1_plus = 21
galvo1_minus = 22
# This will be further populated with the laser ao channels from channel_specs at runtime.

# Devices
[dcam_specs]
ncams = 2 # number of cameras
row_interval = 15e-6 # seconds. Cannot be less then 10 [us].
scan_direction = 'FORWARD' #  BACKWARD for ch2 and FORWARD for ch1
camx = 2304 # number of x camera pixels
camy = 2304 # number of y camera pixels

# <SOMETHING>_kwds will be splatted with **kwds to init the corresponding object.
[daq_driver_kwds]
dev_name = 'Dev1' # NI Card address as it appears to the PC.
output_trigger_name = 'port0/line0'
update_frequency = 4e5 # Hz

[etl_driver_kwds]
port = 'COM4' # COM7 for ch2, COM4 for ch1

[tiger_controller_driver_kwds]
com_port='COM10'

[filter_wheel_kwds]
tiger_axis = 1 # filterwheel axis according to the tigerbox.

# For imaging run estimations.
[estimates]
tiles_per_second = 15
gigabytes_per_image = 0.8
