[imaging_specs]
local_storage_directory = "C:\\test"
external_storage_directory = "Y:\\\\diSPIM"
subject_id = "test"
tile_prefix = "tile"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 15
z_step_size_um = 0.176
volume_x_um = 600
volume_y_um = 400
volume_z_um = 100
laser_wavelengths = [ 488,]
possible_wavelengths = [ 488, 638, 405, 561,]

[tile_specs]
x_field_of_view_um = 405.504
y_field_of_view_um = 405.504
row_count_pixels = 2304
column_count_pixels = 2304
data_type = "uint16"

[design_specs]
slit_width_pixels = 294

[stage_specs]
backlash_reset_distance_um = 4

[waveform_specs]
delay_time = 0.0015
rest_time = 0.005
exposure_time = 0.016

[daq_ao_names_to_channels]
galvo_y_right = 0
galvo_y_left = 1
galvo_x_right = 2
galvo_x_left = 3
etl_left = 4
etl_right = 5
camera_left = 6
camera_right = 7

[daq_driver_kwds]
dev_name = "Dev2"
input_trigger_name = "PFI0"
update_frequency_hz = 400000.0

[tiger_controller_driver_kwds]
com_port = "COM3"

[filter_wheel_left_kwds]
tiger_axis = 0

[filter_wheel_right_kwds]
tiger_axis = 1

[estimates]
tiles_per_second = 15

[tiger_specs.axes]
etl_left_axis = "V"
etl_right_axis = "W"
galvo_left_x_axis = "A"
galvo_left_y_axis = "B"
galvo_right_x_axis = "C"
galvo_right_y_axis = "D"

[channel_specs.405]
driver = "Oxxius"
color = "purple"
prefix = "L6"
filter_index = 1
ao_channel = 12
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.488]
driver = "Oxxius"
color = "blue"
prefix = "L5"
filter_index = 2
ao_channel = 11
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.561]
driver = "Oxxius"
color = "green"
prefix = "L3"
filter_index = 3
ao_channel = 9
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.638]
driver = "Oxxius"
color = "red"
prefix = "L1"
filter_index = 4
ao_channel = 8
disable_voltage = 0.0
enable_voltage = 5.0

[camera_specs.camera_right]
row_interval = 5.867e-6
scan_direction = "FORWARD"
shutter_mode = "LIGHTSHEET"
offset = 0.05
camx = 2304
camy = 2304

[camera_specs.camera_left]
row_interval = 5.867e-6
scan_direction = "BACKWARD"
shutter_mode = "LIGHTSHEET"
offset = 0.0
camx = 2304
camy = 2304

[sample_pose_kwds.axis_map]
x = "y"
y = "z"
z = "x"

[channel_specs.405.etl]
left_offset = 1.7
left_amplitude = 0
right_offset = 1.9
right_amplitude = 0

[channel_specs.405.galvo]
x_left_offset = 2.46
x_left_amplitude = -0.015
x_right_offset = 2.6
x_right_amplitude = -0.015
y_left_offset = 2.3
y_left_amplitude = 1.4
y_right_offset = 2.6
y_right_amplitude = 1.4

[channel_specs.405.kwds]
port = "COMxx"

[channel_specs.488.etl]
left_offset = 1.5
left_amplitude = 0
right_offset = 1.55
right_amplitude = 0

[channel_specs.488.galvo]
x_left_offset = 2.445
x_left_amplitude = -0.018
x_right_offset = 2.595
x_right_amplitude = -0.015
y_left_offset = 2.18
y_left_amplitude = 1.3
y_right_offset = 2.2
y_right_amplitude = 1.3

[channel_specs.488.kwds]
port = "COMxx"

[channel_specs.561.etl]
left_offset = 1.7
left_amplitude = 0
right_offset = 1.9
right_amplitude = 0

[channel_specs.561.galvo]
x_left_offset = 2.46
x_left_amplitude = -0.015
x_right_offset = 2.6
x_right_amplitude = -0.015
y_left_offset = 2.3
y_left_amplitude = 1.4
y_right_offset = 2.6
y_right_amplitude = 1.4

[channel_specs.561.kwds]
port = "COMxx"

[channel_specs.638.etl]
left_offset = 1.7
left_amplitude = 0
right_offset = 1.9
right_amplitude = 0

[channel_specs.638.galvo]
x_left_offset = 2.46
x_left_amplitude = -0.015
x_right_offset = 2.6
x_right_amplitude = -0.015
y_left_offset = 2.3
y_left_amplitude = 1.4
y_right_offset = 2.6
y_right_amplitude = 1.4

[channel_specs.638.kwds]
port = "COMxx"
