[imaging_specs]
local_storage_directory = "C:\\test_dispim"
subject_id = "test"
tile_prefix = "tile"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 15
z_step_size_um = 0.209
volume_x_um = 400.0
volume_y_um = 400.0
volume_z_um = 10
laser_wavelengths = [ 405, 488, 561, 638,]
camera_streams = [ 0,]
external_storage_directory = "Y:\\test_dispim"
filetype = "Zarr"

[tile_specs]
x_field_of_view_um = 686.592
y_field_of_view_um = 686.592
row_count_pixels = 2304
column_count_pixels = 2304
data_type = "uint16"

[design_specs]
slit_width_pixels = 150

[stage_specs]
backlash_reset_distance_um = 4

[waveform_specs]
delay_time = 0
rest_time = 0.004
exposure_time = 0.025
line_time_us = 10.850694444444445

[daq_ao_names_to_channels]
galvo_y = 0
galvo_x = 2
etl = 5
camera = 6

[daq_driver_kwds]
dev_name = "Dev2"
input_trigger_name = "PFI0"
count_trigger_name = "PFI3"
ao_counter_trigger_name = "PFI2"
update_frequency_hz = 400000.0
livestream_frequency_hz = 20

[tiger_controller_driver_kwds]
com_port = "COM3"

[filter_wheel_left_kwds]
tiger_axis = 0

[filter_wheel_kwds]
tiger_axis = 1

[estimates]
tiles_per_second = 15

[camera_specs]
scan_direction = "BACKWARD"
shutter_mode = "LIGHTSHEET"

[tiger_specs.axes]
etl_axis = "W"
galvo_x_axis = "C"
galvo_y_axis = "D"

[channel_specs.405]
driver = "Oxxius"
color = "purple"
prefix = "L6"
filter_index = 1
ao_channel = 12
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.488]
driver = "Oxxius"
color = "blue"
prefix = "L5"
filter_index = 2
ao_channel = 11
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.561]
driver = "Oxxius"
color = "green"
prefix = "L3"
filter_index = 3
ao_channel = 9
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.638]
driver = "Oxxius"
color = "red"
prefix = "L1"
filter_index = 4
ao_channel = 8
disable_voltage = 0.0
enable_voltage = 5.0

[sample_pose_kwds.axis_map]
x = "y"
y = "z"
z = "x"

[channel_specs.405.etl]
offset = 1.75
amplitude = 0

[channel_specs.405.galvo]
x_offset = 2.565
x_amplitude = -0.01
y_offset = 2.4
y_amplitude = 1.4

[channel_specs.405.kwds]
port = "COMxx"

[channel_specs.488.etl]
offset = 1.75
amplitude = 0

[channel_specs.488.galvo]
x_offset = 2.565
x_amplitude = -0.01
y_offset = 2.4
y_amplitude = 1.15

[channel_specs.488.kwds]
port = "COMxx"

[channel_specs.561.etl]
offset = 1.75
amplitude = 0

[channel_specs.561.galvo]
x_offset = 2.56
x_amplitude = -0.02
y_offset = 3.0
y_amplitude = 1.4

[channel_specs.561.kwds]
port = "COMxx"

[channel_specs.638.etl]
offset = 1.75
amplitude = 0

[channel_specs.638.galvo]
x_offset = 2.57
x_amplitude = -0.01
y_offset = 2.4
y_amplitude = 1.15

[channel_specs.638.kwds]
port = "COMxx"
