[imaging_specs]
local_storage_directory = "C:\\dispim_test"
subject_id = "660433"
tile_prefix = "660433"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 15
z_step_size_um = 0.8
volume_x_um = 8500.0
volume_y_um = 300.0
volume_z_um = 8000
laser_wavelengths = [ 405,]
camera_streams = [ 0,]
filetype = "Tiff"
acquisition_style = "sequential"
external_storage_directory = "Z:\\dispim_test"

[experiment_specs]
experimenters_name = "Micah Woodard"
immersion_medium = "PBS"
immersion_medium_refractive_index = 1.33

[tile_specs]
x_field_of_view_um = 686.592
y_field_of_view_um = 686.592
row_count_pixels = 2304
column_count_pixels = 2304
data_type = "uint16"

[design_specs]
slit_width_pixels = 150

[stage_specs]
backlash_reset_distance_um = 4

[waveform_specs]
delay_time = 0
rest_time = 0.004
exposure_time = 0.05
line_time_us = 10.850694444444445
pre_buffer_time_s = 0.0
post_buffer_time_s = 0.0
laser_pre_buffer_time_s = 0.001
laser_post_buffer_time_s = 0.001

[daq_ao_names_to_channels]
galvo_y = 2
galvo_x = 0
etl = 5
camera = 6

[daq_driver_kwds]
dev_name = "Dev1"
input_trigger_name = "PFI0"
count_trigger_name = "PFI3"
ao_counter_trigger_name = "PFI2"
update_frequency_hz = 400000.0
livestream_frequency_hz = 30

[tiger_controller_driver_kwds]
com_port = "COM5"

[filter_wheel_kwds]
tiger_axis = 0

[estimates]
tiles_per_second = 15

[camera_specs]
scan_direction = "BACKWARD"
shutter_mode = "LIGHTSHEET"

[tiger_specs.axes]
etl_left_axis = "V"
etl_right_axis = "W"
galvo_left_x_axis = "A"
galvo_left_y_axis = "B"
galvo_right_x_axis = "C"
galvo_right_y_axis = "D"

[channel_specs.405]
driver = "vortran_laser"
laser = "stradus.StradusLaser"
intensity_mode = "power"
color = "purple"
filter_index = 0
ao_channel = 12
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.488]
driver = "vortran_laser"
laser = "stradus.StradusLaser"
intensity_mode = "power"
color = "blue"
filter_index = 1
ao_channel = 11
disable_voltage = 0.0
enable_voltage = 3.0

[channel_specs.514]
driver = "vortran_laser"
laser = "stradus.StradusLaser"
intensity_mode = "power"
color = "green"
filter_index = 2
ao_channel = 19
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.594]
driver = "obis_laser"
laser = "ObisLS"
intensity_mode = "power"
color = "orange"
filter_index = 4
ao_channel = 17
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.561]
driver = "vortran_laser"
laser = "stradus.StradusLaser"
intensity_mode = "power"
color = "yellowgreen"
filter_index = 3
ao_channel = 9
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.638]
driver = "vortran_laser"
laser = "stradus.StradusLaser"
intensity_mode = "power"
color = "red"
filter_index = 5
ao_channel = 14
disable_voltage = 0.0
enable_voltage = 5.0

[sample_pose_kwds.axis_map]
x = "y"
y = "z"
z = "x"

[channel_specs.405.setup]
set_modulation_mode = "analog"
set_laser_driver_control_mode = "power"
set_external_control = true

[channel_specs.405.etl]
offset = 1.665
amplitude = 0

[channel_specs.405.galvo]
x_offset = 2.534
x_amplitude = 0.0
y_offset = 2.502
y_amplitude = 0.831

[channel_specs.405.kwds]
port = "COM9"

[channel_specs.488.setup]
set_modulation_mode = "digital"
set_laser_driver_control_mode = "power"
set_external_control = false

[channel_specs.488.etl]
offset = 1.75
amplitude = 0.0

[channel_specs.488.galvo]
x_offset = 2.545
x_amplitude = 0.0
y_offset = 2.549
y_amplitude = 0.811

[channel_specs.488.kwds]
port = "COM12"

[channel_specs.514.setup]
set_modulation_mode = "analog"
set_laser_driver_control_mode = "power"
set_external_control = true

[channel_specs.514.etl]
offset = 1.459
amplitude = 0

[channel_specs.514.galvo]
x_offset = 2.534
x_amplitude = -0.02
y_offset = 2.552
y_amplitude = 0.835

[channel_specs.514.kwds]
port = "COMxx"

[channel_specs.594.setup]
set_analog_input_impedance = "AnalogInputImpedanceType.TWO_THOUSAND_OHM"

[channel_specs.594.etl]
offset = 1.727
amplitude = 0

[channel_specs.594.galvo]
x_offset = 2.543
x_amplitude = -0.02
y_offset = 2.544
y_amplitude = 0.813

[channel_specs.594.kwds]
port = "COM13"

[channel_specs.561.setup]
set_modulation_mode = "analog"
set_laser_driver_control_mode = "power"
set_external_control = true

[channel_specs.561.etl]
offset = 1.691
amplitude = 0

[channel_specs.561.galvo]
x_offset = 2.542
x_amplitude = -0.02
y_offset = 2.534
y_amplitude = 0.836

[channel_specs.561.kwds]
port = "COM10"

[channel_specs.638.setup]
set_modulation_mode = "analog"
set_laser_driver_control_mode = "power"
set_external_control = true

[channel_specs.638.etl]
offset = 1.738
amplitude = 0

[channel_specs.638.galvo]
x_offset = 3.036
x_amplitude = -0.01
y_offset = 2.529
y_amplitude = 0.861

[channel_specs.638.kwds]
port = "COM7"
