TomlTemplate = \
{'camera_specs': {'camera_left': {'camx': 2304,
                                  'camy': 2304,
                                  'delay': 0.0,
                                  'row_interval': 5.867e-06,
                                  'scan_direction': 'BACKWARD',
                                  'shutter_mode': 'LIGHTSHEET'},
                  'camera_right': {'camx': 2304,
                                   'camy': 2304,
                                   'delay': 0.001,
                                   'row_interval': 5.867e-06,
                                   'scan_direction': 'FORWARD',
                                   'shutter_mode': 'LIGHTSHEET'}},
 'channel_specs': {'405': {'ao_channel': 12,
                           'color': 'purple',
                           'disable_voltage': 0.0,
                           'driver': 'Oxxius',
                           'enable_voltage': 5.0,
                           'etl': {'left_amplitude': 0,
                                   'left_offset': 1.7,
                                   'right_amplitude': 0,
                                   'right_offset': 1.7},
                           'filter_index': 1,
                           'galvo': {'x_left_amplitude': -0.02,
                                     'x_left_offset': 2.455,
                                     'x_right_amplitude': -0.015,
                                     'x_right_offset': 2.6,
                                     'y_left_amplitude': 1.3,
                                     'y_left_offset': 2.35,
                                     'y_right_amplitude': 1.4,
                                     'y_right_offset': 2.6},
                           'kwds': {'port': 'COMxx'},
                           'prefix': 'L6'},
                   '488': {'ao_channel': 11,
                           'color': 'blue',
                           'disable_voltage': 0.0,
                           'driver': 'Oxxius',
                           'enable_voltage': 5.0,
                           'etl': {'left_amplitude': 0,
                                   'left_offset': 1.45,
                                   'right_amplitude': 0,
                                   'right_offset': 1.55},
                           'filter_index': 2,
                           'galvo': {'x_left_amplitude': -0.013,
                                     'x_left_offset': 2.448,
                                     'x_right_amplitude': -0.018,
                                     'x_right_offset': 2.59,
                                     'y_left_amplitude': 1.3,
                                     'y_left_offset': 2.35,
                                     'y_right_amplitude': 1.4,
                                     'y_right_offset': 2.5},
                           'kwds': {'port': 'COMxx'},
                           'prefix': 'L5'},
                   '561': {'ao_channel': 9,
                           'color': 'green',
                           'disable_voltage': 0.0,
                           'driver': 'Oxxius',
                           'enable_voltage': 5.0,
                           'etl': {'left_amplitude': 0,
                                   'left_offset': 1.5,
                                   'right_amplitude': 0,
                                   'right_offset': 1.7},
                           'filter_index': 3,
                           'galvo': {'x_left_amplitude': -0.013,
                                     'x_left_offset': 2.445,
                                     'x_right_amplitude': -0.015,
                                     'x_right_offset': 2.595,
                                     'y_left_amplitude': 1.3,
                                     'y_left_offset': 2.35,
                                     'y_right_amplitude': 1.4,
                                     'y_right_offset': 2.5},
                           'kwds': {'port': 'COMxx'},
                           'prefix': 'L3'},
                   '638': {'ao_channel': 8,
                           'color': 'red',
                           'disable_voltage': 0.0,
                           'driver': 'Oxxius',
                           'enable_voltage': 5.0,
                           'etl': {'left_amplitude': 0,
                                   'left_offset': 1.5,
                                   'right_amplitude': 0,
                                   'right_offset': 1.9},
                           'filter_index': 4,
                           'galvo': {'x_left_amplitude': -0.013,
                                     'x_left_offset': 2.445,
                                     'x_right_amplitude': -0.015,
                                     'x_right_offset': 2.594,
                                     'y_left_amplitude': 1.3,
                                     'y_left_offset': 2.35,
                                     'y_right_amplitude': 1.4,
                                     'y_right_offset': 2.5},
                           'kwds': {'port': 'COMxx'},
                           'prefix': 'L1'}},
 'daq_ao_names_to_channels': {'camera_left': 7,
                              'camera_right': 6,
                              'etl_left': 4,
                              'etl_right': 5,
                              'galvo_x_left': 3,
                              'galvo_x_right': 2,
                              'galvo_y_left': 1,
                              'galvo_y_right': 0},
 'daq_driver_kwds': {'dev_name': 'Dev2',
                     'input_trigger_name': 'PFI0',
                     'update_frequency_hz': 400000.0},
 'design_specs': {'slit_width_pixels': 400},
 'estimates': {'tiles_per_second': 15},
 'filter_wheel_left_kwds': {'tiger_axis': 0},
 'filter_wheel_right_kwds': {'tiger_axis': 1},
 'imaging_specs': {'external_storage_directory': 'C:\\test',
                   'laser_wavelengths': [405, 488, 561, 638],
                   'local_storage_directory': 'C:\\test',
                   'subject_id': 'test',
                   'tile_overlap_x_percent': 15,
                   'tile_overlap_y_percent': 15,
                   'tile_prefix': 'tile',
                   'volume_x_um': 400.0,
                   'volume_y_um': 205.0,
                   'volume_z_um': 66.5,
                   'z_step_size_um': 0.176},
 'sample_pose_kwds': {'axis_map': {'x': 'y', 'y': 'z', 'z': 'x'}},
 'stage_specs': {'backlash_reset_distance_um': 4},
 'tiger_controller_driver_kwds': {'com_port': 'COM3'},
 'tiger_specs': {'axes': {'etl_left_axis': 'V',
                          'etl_right_axis': 'W',
                          'galvo_left_x_axis': 'A',
                          'galvo_left_y_axis': 'B',
                          'galvo_right_x_axis': 'C',
                          'galvo_right_y_axis': 'D'}},
 'tile_specs': {'column_count_pixels': 2304,
                'data_type': 'uint16',
                'row_count_pixels': 2304,
                'x_field_of_view_um': 405.504,
                'y_field_of_view_um': 405.504},
 'waveform_specs': {'delay_time': 0.006,
                    'exposure_time': 0.025,
                    'line_time_us': 10.850694444444445,
                    'rest_time': 0.004}}
