[imaging_specs]
local_storage_directory = "."
external_storage_directory = "."
subject_id = "test"
tile_prefix = "tile"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 15
z_step_size_um = 0.25
volume_x_um = 2305
volume_y_um = 2305
volume_z_um = 1000
laser_wavelengths = [ 488,]

[tile_specs]
x_field_of_view_um = 2304
y_field_of_view_um = 2304
row_count_pixels = 2304
column_count_pixels = 2304
data_type = "uint16"

[design_specs]
slit_width_pixels = 294

[sample_stage_specs]
backlash_reset_distance_um = 4

[waveform_specs]
delay_time = 0.0015
rest_time = 0.005
exposure_time = 0.012

[daq_ao_names_to_channels]
galvo_y_left = 0
galvo_y_right = 1
galvo_x_left = 2
galvo_x_right = 3
etl_left = 4
etl_right = 5
camera_left = 6
camera_right = 7

[daq_driver_kwds]
dev_name = "Dev1"
output_trigger_name = "port0/line0"
update_frequency = 400000.0

[tiger_controller_driver_kwds]
com_port = "COM10"

[filter_wheel_left_kwds]
tiger_axis = 0

[filter_wheel_right_kwds]
tiger_axis = 1

[estimates]
tiles_per_second = 15

[channel_specs.405]
driver = "Oxxius"
color = "purple"
filter_index = 1
ao_channel = 12
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.488]
driver = "Oxxius"
color = "blue"
filter_index = 2
ao_channel = 11
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.561]
driver = "Oxxius"
color = "green"
filter_index = 3
ao_channel = 9
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.638]
driver = "Oxxius"
color = "red"
filter_index = 4
ao_channel = 8
disable_voltage = 0.0
enable_voltage = 5.0

[camera_specs.camera_right]
row_interval = 5.867e-6
scan_direction = "FORWARD"
camx = 2304
camy = 2304

[camera_specs.camera_left]
row_interval = 5.867e-6
scan_direction = "BACKWARD"
camx = 2304
camy = 2304

[sample_pose_kwds.axis_map]
x = "z"
y = "x"
z = "y"

[channel_specs.405.etl_left]
offset = 1.85
amplitude = 0

[channel_specs.405.etl_right]
offset = 1.65
ampitude = 0

[channel_specs.405.galvo_x_left]
offset = 2.4
amplitude = -0.015

[channel_specs.405.galvo_x_right]
offset = 2.74
amplitude = -0.015

[channel_specs.405.galvo_y_left]
offset = 2.56
amplitude = 1.3

[channel_specs.405.galvo_y_right]
offset = 2.75
amplitude = 1.3

[channel_specs.405.kwds]
port = "COMxx"

[channel_specs.488.etl_left]
offset = 1.85
amplitude = 0

[channel_specs.488.etl_right]
offset = 1.65
ampitude = 0

[channel_specs.488.galvo_x_left]
offset = 2.4
amplitude = -0.015

[channel_specs.488.galvo_x_right]
offset = 2.74
amplitude = -0.015

[channel_specs.488.galvo_y_left]
offset = 2.56
amplitude = 1.3

[channel_specs.488.galvo_y_right]
offset = 2.75
amplitude = 1.3

[channel_specs.488.kwds]
port = "COMxx"

[channel_specs.561.etl_left]
offset = 1.85
amplitude = 0

[channel_specs.561.etl_right]
offset = 1.65
ampitude = 0

[channel_specs.561.galvo_x_left]
offset = 2.4
amplitude = -0.015

[channel_specs.561.galvo_x_right]
offset = 2.74
amplitude = -0.015

[channel_specs.561.galvo_y_left]
offset = 2.56
amplitude = 1.3

[channel_specs.561.galvo_y_right]
offset = 2.75
amplitude = 1.3

[channel_specs.561.kwds]
port = "COMxx"

[channel_specs.638.etl_left]
offset = 1.85
amplitude = 0

[channel_specs.638.etl_right]
offset = 1.65
ampitude = 0

[channel_specs.638.galvo_x_left]
offset = 2.4
amplitude = -0.015

[channel_specs.638.galvo_x_right]
offset = 2.74
amplitude = -0.015

[channel_specs.638.galvo_y_left]
offset = 2.56
amplitude = 1.3

[channel_specs.638.galvo_y_right]
offset = 2.75
amplitude = 1.3

[channel_specs.638.kwds]
port = "COMxx"
